# Generated by Django 4.2.4 on 2023-08-31 08:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Current_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('car_type', models.CharField(choices=[('light vehicle', 'light vehicle'), ('meduim vehicle', 'meduim vehicle'), ('heavy vehicle', 'heavy vehicle')], max_length=50)),
                ('time_in', models.TimeField(auto_now_add=True)),
                ('time_out', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkManage.owner')),
            ],
        ),
    ]
