# Generated by Django 4.2.4 on 2023-08-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
