# Generated by Django 4.2.4 on 2023-08-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkManage', '0003_alter_car_time_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('car_type', models.CharField(choices=[('light vehicle', 'light vehicle'), ('meduim vehicle', 'meduim vehicle'), ('heavy vehicle', 'heavy vehicle')], max_length=50)),
                ('time_in', models.TimeField(auto_now_add=True)),
                ('time_out', models.TimeField()),
                ('time_reserved', models.DurationField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
