# Generated by Django 4.2.4 on 2023-08-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkManage', '0004_current_car_delete_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_car',
            name='time_reserved',
        ),
    ]
