# Generated by Django 4.2.4 on 2023-08-30 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkManage', '0005_remove_current_car_time_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_car',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='current_car',
            name='time_out',
            field=models.TimeField(null=True),
        ),
    ]
