# Generated by Django 4.2.4 on 2023-08-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkManage', '0007_owner_alter_current_car_time_out_current_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_car',
            name='owner',
        ),
        migrations.DeleteModel(
            name='owner',
        ),
    ]
